version: '3'

services:
  celery:
    build: .
    environment:
      CELERY_BROKER_URL: 'amqp://guest:guest@rabbitmq:5672//'

  celery-beat:
    build: .
    entrypoint: celery -A tasks beat
    environment:
      CELERY_BROKER_URL: 'amqp://guest:guest@rabbitmq:5672//'

  rabbitmq:
    image: rabbitmq

